### ISSUE TITLE
Docker Auto-Build Feature

### ISSUE THREAD

**Issue by deshario** [yiisoft/yii2-app-basic#193]
Can i use auto-build feature of docker with docker-compose.yml without DockerFile

My Docker Compose File 
https://github.com/deshario/bloodbank-dockerized/blob/master/docker-compose.yml

### Project Structure
![screen shot 2562-02-07 at 16 04 41](https://user-images.githubusercontent.com/11426727/52400581-1e480780-2af2-11e9-90cf-f2fd3d81bf12.png)

when i try to create repository by selecting auto build options it says Dockerfile not found ! 
In `https://github.com/yiisoft/yii2-app-basic` also there is not `Dockerfile` included. 
what should i do to use auto-build feature when push latest code to master branch.

### DockerHub
![bloodbank](https://user-images.githubusercontent.com/11426727/52400483-d75a1200-2af1-11e9-8ccd-77ce328d75d6.png)

Is it possible to build image or use auto-build feature with docker-compose only. Thanks

**Comment by FabrizioCaldarelli** [comment]
You could use this docker-compose.yml:

```yml
version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=myuser

  web:
    image: yiisoftware/yii-php:7.1-fpm
    environment:
      - PHP_ENABLE_XDEBUG=1
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
      # For composer usage in container; NOTE! There may be performance issues, see also https://github.com/docker/for-mac/issues/77
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - "8100:80"
```

**Comment by deshario** [comment]
@FabrizioCaldarelli you mean i should change image yep ?
 
```
 image: yiisoftware/yii2-php:7.1-apache ====> image: yiisoftware/yii-php:7.1-fpm
```

### New docker-compose.yml

```
version: '2'
services:

  db:
    image: mariadb:10.1
    container_name: bloodbank_DB
    restart: always
    volumes:
      - ./db/initdb/:/docker-entrypoint-initdb.d
      - ./db/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=111222333
      - MYSQL_DATABASE=bloodbank
      - MYSQL_USER=deshario
      - MYSQL_PASSWORD=123456

  php:
    image: yiisoftware/yii-php:7.1-fpm
    container_name: bloodbank_APP
    depends_on:
      - db
    volumes:
      - ./app/:/var/www/html/
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - '8010:80'

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: bloodbank_PMA
    restart: always
    ports:
      - "8020:80"
```
