### ISSUE TITLE
Volume mount path in docker-compose file seems to be broken!

### ISSUE THREAD

**Issue by leninhasda** [yiisoft/yii2-app-basic#194]
### What steps will reproduce the problem?
1. git clone and cd into project
2. run `docker-compose run --rm php composer update --prefer-dist` command

### What's expected?
Composer update should run successfully.

### What do you get instead?
Error message saying that could not find a `composer.json`  file 
```
   ....
   10/12:      http://repo.packagist.org/p/provider-2016$60899c61c13c4a5b597bba66a76ba6398d399be43e6872f4eec8a87c7d82e141.json
    11/12:      http://repo.packagist.org/p/provider-2013$d03bc7951906ea11f1af6fb62aad50997819722eecb3dcdd3711f173feca5622.json
    12/12:      http://repo.packagist.org/p/provider-2018-10$c577c6e31c5be0e9c6eac82068568eaa7985007bf1890222fab4393e7f5b0b34.json
    Finished: success: 12, skipped: 0, failure: 0, total: 12
Composer could not find a composer.json file in /var/www/html
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

### Additional info
When I changed volume mount path to this it worked. I think current mount path is incorrect.
```
version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # - ./:/app:delegated <--- remove this
      - ./:/var/www/html # <--- this worked
    ports:
      - '8000:80'
```
